### ISSUE TITLE
Viewmodel context contained in self is lost

### ISSUE THREAD

**Issue by Doomape** [sumitkm/BuildingSpaUsingKO#2]
Here is a screenshot of the issue: http://prntscr.com/8rdsww.

Why is this happening?

**Comment by sumitkm** [comment]
Hi,
First up, many apologies for the delay in response. I guess you would have figured it out already, but the reason you are getting the 'incorrect' self is because in the following code, the function is called in context of the window when the click happens. 

```
self.testclick( function() {
// self is incorrect (as shown in your screenshot)

});
```

Easy way to fix it is to bind self to the function

```
self.testclick( function() {
/// You should have the correct instance of self now

}.bind(self));
```

Hope this helps.

**Comment by sumitkm** [comment]
Closing issue, feel free to reopen if unresolved.
